// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omlwkftjhactcurxeqgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tbHdrZnRqaGFjdGN1cnhlcWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMDU5MzIsImV4cCI6MjA2NzY4MTkzMn0.ahUKmTO7m0I0ZnjpjuDvvX-qNGtcZIkXKJseOk75TyY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});